version: '3.8'

services:
    php-apache:
        container_name: "${CONTAINER_NAME_PREFIX}-apache-php"
        build: .
        restart: always
        depends_on:
            - db
        volumes:
            - .:/var/www/html
        ports:
            - "8000:80"

    db:
        container_name: "${CONTAINER_NAME_PREFIX}-mysql"
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db:/var/lib/mysql
        ports:
            - "3307:3306"

volumes:
    db:
